# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      #- id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.3.2" # or specific git tag
    hooks:
      - id: prettier

  - repo: https://github.com/ekans/prettier-java-pre-commit-hook
    rev: master
    hooks:
      - id: prettier-java

  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: master # or specific git tag
  #   hooks:
  #     - id: markdownlint # Configure in .mdlrc
  #       args: ["-g"]
  # TODO looks like csslint doesn't support grid
  # - repo: https://github.com/pre-commit/mirrors-csslint
  #   rev: v1.0.5
  #   hooks:
  #     - id: csslint

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        language: docker_image
        entry: koalaman/shellcheck:stable
        types: [shell]
        args: ["-C", "-x"]
        exclude: gradlew
      - id: shfmt
        name: shfmt
        language: docker_image
        entry: mvdan/shfmt
        types: [shell]
        args: ["-i", "4", "-ci", "-sr", "-w"]
        exclude: gradlew
  # uncomment below to help debug pre-commit checks
  # - repo: meta
  #   hooks:
  #       - id: check-hooks-apply
  #       - id: check-useless-excludes
  #       - id: identity
  # - repo: git@github.com:Yelp/detect-secrets
  #   rev: v0.13.1
  #   hooks:
  #     - id: detect-secrets
  #       args: ["--baseline", ".secrets.baseline"]
  #       exclude: .*/tests/.*
